
spring:
  application:
    name: file-loader
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: file_upload_group
    producer:
      bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:h2:mem:file-loader
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none

file:
  upload:
    min:
      delay: 60_000
    max:
      delay: 100_000
