DROP TABLE IF EXISTS file_upload_entity;

CREATE TABLE FILE_UPLOAD_ENTITY (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    request_id VARCHAR(255) NOT NULL,
    file_link VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL
);